scan_filter_chain:

- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 10
    max_angle: 170
    neighbors: 5
    window: 1

- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -2.300
    upper_angle: 2.300

- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.200
    max_x:  0.200
    min_y: -0.20
    max_y: 0.20
    min_z: -1.0
    max_z: 1.0

