local_costmap:
   global_frame: map
   #global_frame: /odom_combined
   robot_base_frame: base_link
   update_frequency: 8.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 9.0
   height: 9.0
   resolution: 0.05
   transform_tolerance: 1.0
   map_type: costmap

   plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer, type:  "costmap_2d::ObstacleLayer"}
   # - {name: inflation_layer, type:  "costmap_2d::InflationLayer"}

#- {name: sonar_layer, type:  "range_sensor_layer::RangeSensorLayer"} 

